version: '3.8'

services:
  # MySQL database
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: ecom_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1111
    depends_on:
      - db

  # FastAPI Backend
  backend:
    image: suttipong2546/project_ecom:latest
    platform: linux/amd64
    restart: always
    ports:
      - "80:8000"  # เปิดหน้าเว็บได้ที่ http://<ip>
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1111
      - DB_NAME=ecom_db
    volumes:
      - ./uploads:/app/uploads
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...' &&
        while ! nc -z db 3306; do
          sleep 1
        done &&
        echo 'MySQL is ready!' &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

volumes:
  mysql_data:
